"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.version = exports.ConsoleLogger = exports.setLogger = void 0;
const tslib_1 = require("tslib");
var log_js_1 = require("./log.js");
Object.defineProperty(exports, "setLogger", { enumerable: true, get: function () { return log_js_1.setLogger; } });
Object.defineProperty(exports, "ConsoleLogger", { enumerable: true, get: function () { return log_js_1.ConsoleLogger; } });
tslib_1.__exportStar(require("./convert.js"), exports);
var version_js_1 = require("./version.js");
Object.defineProperty(exports, "version", { enumerable: true, get: function () { return tslib_1.__importDefault(version_js_1).default; } });
